### ISSUE TITLE
Test Execution creates error messages

### ISSUE THREAD

**Issue by test-fullautomation** [test-fullautomation/RobotFramework_AIO#150]
Latest nightly build:
causes
```
PS C:\Data\Git\bits_rf\ta_framework_dev>  c:; cd 'c:\Data\Git\bits_rf\ta_framework_dev'; & 'C:\Users\tia2hi\AppData\Local\Temp\rf-ls-run\run_env_00_bljm_zc6.bat' '-u' 'c:\RobotFramework\robotvscode\data\extensions\robocorp.robotframework-lsp-1.7.3\src\robotframework_debug_adapter\run_robot__main__.py' '--port' '55268' '--no-debug' '--listener=robotframework_debug_adapter.events_listener.EventsListenerV2' '--listener=robotframework_debug_adapter.events_listener.EventsListenerV3' '--listener' 'C:\Data\Git\bits_rf\ta_framework_dev/code/ta_framework/generic/framework/report/csv/update.py' '--listener' 'C:\Data\Git\bits_rf\ta_framework_dev/code/ta_framework/generic/framework/report/mbits/update.py' '-A' 'C:\Data\Git\bits_rf\ta_framework_dev/.vscode/arguments.tmp' '--pythonpath' 'c:\Data\Git\bits_rf\ta_framework_dev' '--pythonpath' 'c:\Data\Git\bits_rf\ta_framework_dev/code/ta_framework' '--pythonpath' 'C:\BITS_Platform' '--pythonpath' 'C:\BITS\db_client/interfaces' '--variable' 'TESTBENCH_CONFIG_PATH:project/testbench/bench_local' '--variable' 'SUT_CONFIG_PATH:project/sut/group_a/group_aa/variant_aaa' '--variable' 'TAF_PATH:c:\Data\Git\bits_rf\ta_framework_dev/code/ta_framework' '--variable' 'TEST_PATH:c:\Data\Git\bits_rf\ta_framework_dev/test' '--variable' 'WS_PATH:c:\Data\Git\bits_rf\ta_framework_dev' '--variable' 'BP_TEST_PATH:c:\Data\Git\bits_rf\ta_framework_dev/code' '--variable' 'BP_PATH:C:\BITS_Platform' '--variable' 'DB_PATH:C:\BITS\db_client' '--prerunmodifier=robotframework_debug_adapter.prerun_modifiers.FilteringTestsSuiteVisitor' 'c:\Data\Git\bits_rf\ta_framework_dev\code\experiments\tia2hi\configuration\project\test\suites\simple.robot' 
==============================================================================
Simple :: Simple test which triggers configuration parameter initialization   
==============================================================================
Create simple configuration :: Run a simple isolated configuration    robot: 2023-09-21 09:58:55 UTC pid: 17932 - Write from robot to dap (_RobotTargetComm) - EXCEPTION - robocorp_ls_core.debug_adapter_core.debug_adapter_threads
Error serializing <robocorp_ls_core.debug_adapter_core.dap.dap_schema.StartSuiteEvent object at 0x0000025C7E60E040> to json.


TAFLOG: Configuration started ...
.Traceback (most recent call last):
  File "c:\RobotFramework\robotvscode\data\extensions\robocorp.robotframework-lsp-1.7.3\src\robotframework_ls\vendored\robocorp_ls_core\debug_adapter_core\debug_adapter_threads.py", line 249, in writer_thread
    to_write = to_json(update_ids_to_dap=update_ids_to_dap)
  File "c:\RobotFramework\robotvscode\data\extensions\robocorp.robotframework-lsp-1.7.3\src\robotframework_ls\vendored\robocorp_ls_core\debug_adapter_core\dap\dap_base_schema.py", line 36, in to_json
    return json.dumps(self.to_dict(update_ids_to_dap=update_ids_to_dap))
  File "C:\RobotFramework\python39\lib\json\__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "C:\RobotFramework\python39\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\RobotFramework\python39\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\RobotFramework\python39\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type WindowsPath is not JSON serializable
robot: 2023-09-21 09:58:55 UTC pid: 17932 - Write from robot to dap (_RobotTargetComm) - EXCEPTION - robocorp_ls_core.debug_adapter_core.debug_adapter_threads
Error serializing <robocorp_ls_core.debug_adapter_core.dap.dap_schema.StartTestEvent object at 0x0000025C7E60E1C0> to json.

Traceback (most recent call last):
  File "c:\RobotFramework\robotvscode\data\extensions\robocorp.robotframework-lsp-1.7.3\src\robotframework_ls\vendored\robocorp_ls_core\debug_adapter_core\debug_adapter_threads.py", line 249, in writer_thread
    to_write = to_json(update_ids_to_dap=update_ids_to_dap)
  File "c:\RobotFramework\robotvscode\data\extensions\robocorp.robotframework-lsp-1.7.3\src\robotframework_ls\vendored\robocorp_ls_core\debug_adapter_core\dap\dap_base_schema.py", line 36, in to_json
    return json.dumps(self.to_dict(update_ids_to_dap=update_ids_to_dap))
  File "C:\RobotFramework\python39\lib\json\__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "C:\RobotFramework\python39\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\RobotFramework\python39\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\RobotFramework\python39\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type WindowsPath is not JSON serializable
robot: 2023-09-21 09:58:55 UTC pid: 17932 - Write from robot to dap (_RobotTargetComm) - EXCEPTION - robocorp_ls_core.debug_adapter_core.debug_adapter_threads
Error serializing <robocorp_ls_core.debug_adapter_core.dap.dap_schema.LogMessageEvent object at 0x0000025C7E60E1C0> to json.

Traceback (most recent call last):
  File "c:\RobotFramework\robotvscode\data\extensions\robocorp.robotframework-lsp-1.7.3\src\robotframework_ls\vendored\robocorp_ls_core\debug_adapter_core\debug_adapter_threads.py", line 249, in writer_thread
    to_write = to_json(update_ids_to_dap=update_ids_to_dap)
  File "c:\RobotFramework\robotvscode\data\extensions\robocorp.robotframework-lsp-1.7.3\src\robotframework_ls\vendored\robocorp_ls_core\debug_adapter_core\dap\dap_base_schema.py", line 36, in to_json
    return json.dumps(self.to_dict(update_ids_to_dap=update_ids_to_dap))
  File "C:\RobotFramework\python39\lib\json\__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "C:\RobotFramework\python39\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\RobotFramework\python39\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\RobotFramework\python39\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type WindowsPath is not JSON serializable
robot: 2023-09-21 09:58:56 UTC pid: 17932 - Write from robot to dap (_RobotTargetComm) - EXCEPTION - robocorp_ls_core.debug_adapter_core.debug_adapter_threads
Error serializing <robocorp_ls_core.debug_adapter_core.dap.dap_schema.LogMessageEvent object at 0x0000025C7E7AD3A0> to json.

Traceback (most recent call last):
  File "c:\RobotFramework\robotvscode\data\extensions\robocorp.robotframework-lsp-1.7.3\src\robotframework_ls\vendored\robocorp_ls_core\debug_adapter_core\debug_adapter_threads.py", line 249, in writer_thread
    to_write = to_json(update_ids_to_dap=update_ids_to_dap)
  File "c:\RobotFramework\robotvscode\data\extensions\robocorp.robotframework-lsp-1.7.3\src\robotframework_ls\vendored\robocorp_ls_core\debug_adapter_core\dap\dap_base_schema.py", line 36, in to_json
    return json.dumps(self.to_dict(update_ids_to_dap=update_ids_to_dap))
  File "C:\RobotFramework\python39\lib\json\__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "C:\RobotFramework\python39\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\RobotFramework\python39\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\RobotFramework\python39\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type WindowsPath is not JSON serializable
robot: 2023-09-21 09:58:56 UTC pid: 17932 - Write from robot to dap (_RobotTargetComm) - EXCEPTION - robocorp_ls_core.debug_adapter_core.debug_adapter_threads
Error serializing <robocorp_ls_core.debug_adapter_core.dap.dap_schema.LogMessageEvent object at 0x0000025C7E7AD4C0> to json.

.
TAFLOG: Configuration completed.
Traceback (most recent call last):
  File "c:\RobotFramework\robotvscode\data\extensions\robocorp.robotframework-lsp-1.7.3\src\robotframework_ls\vendored\robocorp_ls_core\debug_adapter_core\debug_adapter_threads.py", line 249, in writer_thread
    to_write = to_json(update_ids_to_dap=update_ids_to_dap)
.  File "c:\RobotFramework\robotvscode\data\extensions\robocorp.robotframework-lsp-1.7.3\src\robotframework_ls\vendored\robocorp_ls_core\debug_adapter_core\dap\dap_base_schema.py", line 36, in to_json
    return json.dumps(self.to_dict(update_ids_to_dap=update_ids_to_dap))
  File "C:\RobotFramework\python39\lib\json\__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "C:\RobotFramework\python39\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\RobotFramework\python39\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
Create simple configuration :: Run a simple isolated configuration      File "C:\RobotFramework\python39\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type WindowsPath is not JSON serializable
| PASS |
------------------------------------------------------------------------------
robot: 2023-09-21 09:58:56 UTC pid: 17932 - Write from robot to dap (_RobotTargetComm) - EXCEPTION - robocorp_ls_core.debug_adapter_core.debug_adapter_threads
Error serializing <robocorp_ls_core.debug_adapter_core.dap.dap_schema.LogMessageEvent object at 0x0000025C7E7AD580> to json.

Simple :: Simple test which triggers configuration parameter initi... | PASS |
1 test, 1 passed, 0 failed, 0 unknown
Traceback (most recent call last):
  File "c:\RobotFramework\robotvscode\data\extensions\robocorp.robotframework-lsp-1.7.3\src\robotframework_ls\vendored\robocorp_ls_core\debug_adapter_core\debug_adapter_threads.py", line 249, in writer_thread
    to_write = to_json(update_ids_to_dap=update_ids_to_dap)
==============================================================================
  File "c:\RobotFramework\robotvscode\data\extensions\robocorp.robotframework-lsp-1.7.3\src\robotframework_ls\vendored\robocorp_ls_core\debug_adapter_core\dap\dap_base_schema.py", line 36, in to_json
    return json.dumps(self.to_dict(update_ids_to_dap=update_ids_to_dap))
  File "C:\RobotFramework\python39\lib\json\__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
Debug:   C:\Data\Git\bits_rf\ta_framework_dev\results\simple_20230921_095852\log.txt
  File "C:\RobotFramework\python39\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\RobotFramework\python39\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\RobotFramework\python39\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type WindowsPath is not JSON serializable
robot: 2023-09-21 09:58:56 UTC pid: 17932 - Write from robot to dap (_RobotTargetComm) - EXCEPTION - robocorp_ls_core.debug_adapter_core.debug_adapter_threads
Error serializing <robocorp_ls_core.debug_adapter_core.dap.dap_schema.LogMessageEvent object at 0x0000025C7E7AD640> to json.

Traceback (most recent call last):
  File "c:\RobotFramework\robotvscode\data\extensions\robocorp.robotframework-lsp-1.7.3\src\robotframework_ls\vendored\robocorp_ls_core\debug_adapter_core\debug_adapter_threads.py", line 249, in writer_thread
    to_write = to_json(update_ids_to_dap=update_ids_to_dap)
  File "c:\RobotFramework\robotvscode\data\extensions\robocorp.robotframework-lsp-1.7.3\src\robotframework_ls\vendored\robocorp_ls_core\debug_adapter_core\dap\dap_base_schema.py", line 36, in to_json
    return json.dumps(self.to_dict(update_ids_to_dap=update_ids_to_dap))
  File "C:\RobotFramework\python39\lib\json\__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "C:\RobotFramework\python39\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\RobotFramework\python39\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\RobotFramework\python39\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type WindowsPath is not JSON serializable
robot: 2023-09-21 09:58:56 UTC pid: 17932 - Write from robot to dap (_RobotTargetComm) - EXCEPTION - robocorp_ls_core.debug_adapter_core.debug_adapter_threads
Error serializing <robocorp_ls_core.debug_adapter_core.dap.dap_schema.LogMessageEvent object at 0x0000025C7E7AD880> to json.

Traceback (most recent call last):
  File "c:\RobotFramework\robotvscode\data\extensions\robocorp.robotframework-lsp-1.7.3\src\robotframework_ls\vendored\robocorp_ls_core\debug_adapter_core\debug_adapter_threads.py", line 249, in writer_thread
    to_write = to_json(update_ids_to_dap=update_ids_to_dap)
  File "c:\RobotFramework\robotvscode\data\extensions\robocorp.robotframework-lsp-1.7.3\src\robotframework_ls\vendored\robocorp_ls_core\debug_adapter_core\dap\dap_base_schema.py", line 36, in to_json
    return json.dumps(self.to_dict(update_ids_to_dap=update_ids_to_dap))
  File "C:\RobotFramework\python39\lib\json\__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "C:\RobotFramework\python39\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\RobotFramework\python39\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\RobotFramework\python39\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type WindowsPath is not JSON serializable
robot: 2023-09-21 09:58:56 UTC pid: 17932 - Write from robot to dap (_RobotTargetComm) - EXCEPTION - robocorp_ls_core.debug_adapter_core.debug_adapter_threads
Error serializing <robocorp_ls_core.debug_adapter_core.dap.dap_schema.LogMessageEvent object at 0x0000025C7E7ADA00> to json.

Output:  C:\Data\Git\bits_rf\ta_framework_dev\results\simple_20230921_095852\output.xml
Traceback (most recent call last):
  File "c:\RobotFramework\robotvscode\data\extensions\robocorp.robotframework-lsp-1.7.3\src\robotframework_ls\vendored\robocorp_ls_core\debug_adapter_core\debug_adapter_threads.py", line 249, in writer_thread
    to_write = to_json(update_ids_to_dap=update_ids_to_dap)
  File "c:\RobotFramework\robotvscode\data\extensions\robocorp.robotframework-lsp-1.7.3\src\robotframework_ls\vendored\robocorp_ls_core\debug_adapter_core\dap\dap_base_schema.py", line 36, in to_json
    return json.dumps(self.to_dict(update_ids_to_dap=update_ids_to_dap))
  File "C:\RobotFramework\python39\lib\json\__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "C:\RobotFramework\python39\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\RobotFramework\python39\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\RobotFramework\python39\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type WindowsPath is not JSON serializable
robot: 2023-09-21 09:58:56 UTC pid: 17932 - Write from robot to dap (_RobotTargetComm) - EXCEPTION - robocorp_ls_core.debug_adapter_core.debug_adapter_threads
Error serializing <robocorp_ls_core.debug_adapter_core.dap.dap_schema.LogMessageEvent object at 0x0000025C7E7ADB80> to json.

Traceback (most recent call last):
  File "c:\RobotFramework\robotvscode\data\extensions\robocorp.robotframework-lsp-1.7.3\src\robotframework_ls\vendored\robocorp_ls_core\debug_adapter_core\debug_adapter_threads.py", line 249, in writer_thread
    to_write = to_json(update_ids_to_dap=update_ids_to_dap)
  File "c:\RobotFramework\robotvscode\data\extensions\robocorp.robotframework-lsp-1.7.3\src\robotframework_ls\vendored\robocorp_ls_core\debug_adapter_core\dap\dap_base_schema.py", line 36, in to_json
    return json.dumps(self.to_dict(update_ids_to_dap=update_ids_to_dap))
  File "C:\RobotFramework\python39\lib\json\__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "C:\RobotFramework\python39\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\RobotFramework\python39\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\RobotFramework\python39\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type WindowsPath is not JSON serializable
robot: 2023-09-21 09:58:56 UTC pid: 17932 - Write from robot to dap (_RobotTargetComm) - EXCEPTION - robocorp_ls_core.debug_adapter_core.debug_adapter_threads
Error serializing <robocorp_ls_core.debug_adapter_core.dap.dap_schema.LogMessageEvent object at 0x0000025C7E7ADB20> to json.

Traceback (most recent call last):
  File "c:\RobotFramework\robotvscode\data\extensions\robocorp.robotframework-lsp-1.7.3\src\robotframework_ls\vendored\robocorp_ls_core\debug_adapter_core\debug_adapter_threads.py", line 249, in writer_thread
    to_write = to_json(update_ids_to_dap=update_ids_to_dap)
  File "c:\RobotFramework\robotvscode\data\extensions\robocorp.robotframework-lsp-1.7.3\src\robotframework_ls\vendored\robocorp_ls_core\debug_adapter_core\dap\dap_base_schema.py", line 36, in to_json
    return json.dumps(self.to_dict(update_ids_to_dap=update_ids_to_dap))
  File "C:\RobotFramework\python39\lib\json\__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "C:\RobotFramework\python39\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\RobotFramework\python39\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\RobotFramework\python39\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type WindowsPath is not JSON serializable
robot: 2023-09-21 09:58:56 UTC pid: 17932 - Write from robot to dap (_RobotTargetComm) - EXCEPTION - robocorp_ls_core.debug_adapter_core.debug_adapter_threads
Error serializing <robocorp_ls_core.debug_adapter_core.dap.dap_schema.LogMessageEvent object at 0x0000025C7E7ADD00> to json.

Traceback (most recent call last):
  File "c:\RobotFramework\robotvscode\data\extensions\robocorp.robotframework-lsp-1.7.3\src\robotframework_ls\vendored\robocorp_ls_core\debug_adapter_core\debug_adapter_threads.py", line 249, in writer_thread
    to_write = to_json(update_ids_to_dap=update_ids_to_dap)
  File "c:\RobotFramework\robotvscode\data\extensions\robocorp.robotframework-lsp-1.7.3\src\robotframework_ls\vendored\robocorp_ls_core\debug_adapter_core\dap\dap_base_schema.py", line 36, in to_json
    return json.dumps(self.to_dict(update_ids_to_dap=update_ids_to_dap))
  File "C:\RobotFramework\python39\lib\json\__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "C:\RobotFramework\python39\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\RobotFramework\python39\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\RobotFramework\python39\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type WindowsPath is not JSON serializable
robot: 2023-09-21 09:58:56 UTC pid: 17932 - Write from robot to dap (_RobotTargetComm) - EXCEPTION - robocorp_ls_core.debug_adapter_core.debug_adapter_threads
Error serializing <robocorp_ls_core.debug_adapter_core.dap.dap_schema.LogMessageEvent object at 0x0000025C7E7ADC40> to json.

Traceback (most recent call last):
  File "c:\RobotFramework\robotvscode\data\extensions\robocorp.robotframework-lsp-1.7.3\src\robotframework_ls\vendored\robocorp_ls_core\debug_adapter_core\debug_adapter_threads.py", line 249, in writer_thread
    to_write = to_json(update_ids_to_dap=update_ids_to_dap)
  File "c:\RobotFramework\robotvscode\data\extensions\robocorp.robotframework-lsp-1.7.3\src\robotframework_ls\vendored\robocorp_ls_core\debug_adapter_core\dap\dap_base_schema.py", line 36, in to_json
    return json.dumps(self.to_dict(update_ids_to_dap=update_ids_to_dap))
  File "C:\RobotFramework\python39\lib\json\__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "C:\RobotFramework\python39\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\RobotFramework\python39\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\RobotFramework\python39\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type WindowsPath is not JSON serializable
robot: 2023-09-21 09:58:56 UTC pid: 17932 - Write from robot to dap (_RobotTargetComm) - EXCEPTION - robocorp_ls_core.debug_adapter_core.debug_adapter_threads
Error serializing <robocorp_ls_core.debug_adapter_core.dap.dap_schema.LogMessageEvent object at 0x0000025C7E7ADFA0> to json.

Traceback (most recent call last):
  File "c:\RobotFramework\robotvscode\data\extensions\robocorp.robotframework-lsp-1.7.3\src\robotframework_ls\vendored\robocorp_ls_core\debug_adapter_core\debug_adapter_threads.py", line 249, in writer_thread
    to_write = to_json(update_ids_to_dap=update_ids_to_dap)
  File "c:\RobotFramework\robotvscode\data\extensions\robocorp.robotframework-lsp-1.7.3\src\robotframework_ls\vendored\robocorp_ls_core\debug_adapter_core\dap\dap_base_schema.py", line 36, in to_json
    return json.dumps(self.to_dict(update_ids_to_dap=update_ids_to_dap))
  File "C:\RobotFramework\python39\lib\json\__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "C:\RobotFramework\python39\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\RobotFramework\python39\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\RobotFramework\python39\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type WindowsPath is not JSON serializable
robot: 2023-09-21 09:58:56 UTC pid: 17932 - Write from robot to dap (_RobotTargetComm) - EXCEPTION - robocorp_ls_core.debug_adapter_core.debug_adapter_threads
Error serializing <robocorp_ls_core.debug_adapter_core.dap.dap_schema.LogMessageEvent object at 0x0000025C7E7BF040> to json.

Traceback (most recent call last):
  File "c:\RobotFramework\robotvscode\data\extensions\robocorp.robotframework-lsp-1.7.3\src\robotframework_ls\vendored\robocorp_ls_core\debug_adapter_core\debug_adapter_threads.py", line 249, in writer_thread
    to_write = to_json(update_ids_to_dap=update_ids_to_dap)
  File "c:\RobotFramework\robotvscode\data\extensions\robocorp.robotframework-lsp-1.7.3\src\robotframework_ls\vendored\robocorp_ls_core\debug_adapter_core\dap\dap_base_schema.py", line 36, in to_json
    return json.dumps(self.to_dict(update_ids_to_dap=update_ids_to_dap))
  File "C:\RobotFramework\python39\lib\json\__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "C:\RobotFramework\python39\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\RobotFramework\python39\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\RobotFramework\python39\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type WindowsPath is not JSON serializable
robot: 2023-09-21 09:58:56 UTC pid: 17932 - Write from robot to dap (_RobotTargetComm) - EXCEPTION - robocorp_ls_core.debug_adapter_core.debug_adapter_threads
Error serializing <robocorp_ls_core.debug_adapter_core.dap.dap_schema.LogMessageEvent object at 0x0000025C7E7AD3A0> to json.

Traceback (most recent call last):
  File "c:\RobotFramework\robotvscode\data\extensions\robocorp.robotframework-lsp-1.7.3\src\robotframework_ls\vendored\robocorp_ls_core\debug_adapter_core\debug_adapter_threads.py", line 249, in writer_thread
    to_write = to_json(update_ids_to_dap=update_ids_to_dap)
  File "c:\RobotFramework\robotvscode\data\extensions\robocorp.robotframework-lsp-1.7.3\src\robotframework_ls\vendored\robocorp_ls_core\debug_adapter_core\dap\dap_base_schema.py", line 36, in to_json
    return json.dumps(self.to_dict(update_ids_to_dap=update_ids_to_dap))
  File "C:\RobotFramework\python39\lib\json\__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "C:\RobotFramework\python39\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\RobotFramework\python39\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\RobotFramework\python39\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type WindowsPath is not JSON serializable
robot: 2023-09-21 09:58:56 UTC pid: 17932 - Write from robot to dap (_RobotTargetComm) - EXCEPTION - robocorp_ls_core.debug_adapter_core.debug_adapter_threads
Error serializing <robocorp_ls_core.debug_adapter_core.dap.dap_schema.LogMessageEvent object at 0x0000025C7E7BF100> to json.

Traceback (most recent call last):
  File "c:\RobotFramework\robotvscode\data\extensions\robocorp.robotframework-lsp-1.7.3\src\robotframework_ls\vendored\robocorp_ls_core\debug_adapter_core\debug_adapter_threads.py", line 249, in writer_thread
    to_write = to_json(update_ids_to_dap=update_ids_to_dap)
  File "c:\RobotFramework\robotvscode\data\extensions\robocorp.robotframework-lsp-1.7.3\src\robotframework_ls\vendored\robocorp_ls_core\debug_adapter_core\dap\dap_base_schema.py", line 36, in to_json
    return json.dumps(self.to_dict(update_ids_to_dap=update_ids_to_dap))
  File "C:\RobotFramework\python39\lib\json\__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "C:\RobotFramework\python39\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\RobotFramework\python39\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\RobotFramework\python39\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type WindowsPath is not JSON serializable
robot: 2023-09-21 09:58:56 UTC pid: 17932 - Write from robot to dap (_RobotTargetComm) - EXCEPTION - robocorp_ls_core.debug_adapter_core.debug_adapter_threads
Error serializing <robocorp_ls_core.debug_adapter_core.dap.dap_schema.LogMessageEvent object at 0x0000025C7E7BF220> to json.

Traceback (most recent call last):
  File "c:\RobotFramework\robotvscode\data\extensions\robocorp.robotframework-lsp-1.7.3\src\robotframework_ls\vendored\robocorp_ls_core\debug_adapter_core\debug_adapter_threads.py", line 249, in writer_thread
    to_write = to_json(update_ids_to_dap=update_ids_to_dap)
  File "c:\RobotFramework\robotvscode\data\extensions\robocorp.robotframework-lsp-1.7.3\src\robotframework_ls\vendored\robocorp_ls_core\debug_adapter_core\dap\dap_base_schema.py", line 36, in to_json
    return json.dumps(self.to_dict(update_ids_to_dap=update_ids_to_dap))
  File "C:\RobotFramework\python39\lib\json\__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "C:\RobotFramework\python39\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\RobotFramework\python39\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\RobotFramework\python39\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type WindowsPath is not JSON serializable
robot: 2023-09-21 09:58:56 UTC pid: 17932 - Write from robot to dap (_RobotTargetComm) - EXCEPTION - robocorp_ls_core.debug_adapter_core.debug_adapter_threads
Error serializing <robocorp_ls_core.debug_adapter_core.dap.dap_schema.EndTestEvent object at 0x0000025C7E60E160> to json.

Traceback (most recent call last):
  File "c:\RobotFramework\robotvscode\data\extensions\robocorp.robotframework-lsp-1.7.3\src\robotframework_ls\vendored\robocorp_ls_core\debug_adapter_core\debug_adapter_threads.py", line 249, in writer_thread
    to_write = to_json(update_ids_to_dap=update_ids_to_dap)
  File "c:\RobotFramework\robotvscode\data\extensions\robocorp.robotframework-lsp-1.7.3\src\robotframework_ls\vendored\robocorp_ls_core\debug_adapter_core\dap\dap_base_schema.py", line 36, in to_json
    return json.dumps(self.to_dict(update_ids_to_dap=update_ids_to_dap))
  File "C:\RobotFramework\python39\lib\json\__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "C:\RobotFramework\python39\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\RobotFramework\python39\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\RobotFramework\python39\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type WindowsPath is not JSON serializable
robot: 2023-09-21 09:58:56 UTC pid: 17932 - Write from robot to dap (_RobotTargetComm) - EXCEPTION - robocorp_ls_core.debug_adapter_core.debug_adapter_threads
Error serializing <robocorp_ls_core.debug_adapter_core.dap.dap_schema.EndSuiteEvent object at 0x0000025C7E60E100> to json.

Log:     C:\Data\Git\bits_rf\ta_framework_dev\results\simple_20230921_095852\log.html
Traceback (most recent call last):
  File "c:\RobotFramework\robotvscode\data\extensions\robocorp.robotframework-lsp-1.7.3\src\robotframework_ls\vendored\robocorp_ls_core\debug_adapter_core\debug_adapter_threads.py", line 249, in writer_thread
    to_write = to_json(update_ids_to_dap=update_ids_to_dap)
  File "c:\RobotFramework\robotvscode\data\extensions\robocorp.robotframework-lsp-1.7.3\src\robotframework_ls\vendored\robocorp_ls_core\debug_adapter_core\dap\dap_base_schema.py", line 36, in to_json
    return json.dumps(self.to_dict(update_ids_to_dap=update_ids_to_dap))
  File "C:\RobotFramework\python39\lib\json\__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "C:\RobotFramework\python39\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\RobotFramework\python39\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\RobotFramework\python39\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type WindowsPath is not JSON serializable
Report:  C:\Data\Git\bits_rf\ta_framework_dev\results\simple_20230921_095852\report.html
-- Closing logging streams --
PS C:\Data\Git\bits_rf\ta_framework_dev>
```

**Comment by test-fullautomation** [comment]
Used files are here:

[ta_framework_dev.zip](https://github.com/test-fullautomation/RobotFramework_AIO/files/12683483/ta_framework_dev.zip)

**Comment by test-fullautomation** [comment]
solved and already merged.
